### ISSUE TITLE
Is this awesome lib maintained?

### ISSUE THREAD

**Issue by shubhang93** [mrphu3074/realm-query#10]
First of all, I must say this is a much better way of writing realm queries for react-native, Thanks a ton for this lib. I just want to know if it is still being maintained, because I am thinking of using it in production.

**Comment by mrphu3074** [comment]
@shubhang93 I still using my lib in my applications. But I don't have much time to maintain or develop features. But I have a plan to improve this lib without break changes or few API changes.
