### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by chetmurphy** [mrphu3074/realm-query#2]
Description for findAll is not correct. 

findAll(): ReamResults
**Returns the average of a given field**
Finds all objects that fulfill the query conditions

It should read:

findAll(): ReamResults
Finds all objects that fulfill the query conditions

**Comment by mrphu3074** [comment]
@chetmurphy thank you so much.
Let me fix issue 2 + 3

**Comment by chetmurphy** [comment]
Thanks for your quick response.
