### ISSUE TITLE
Realm Asynchronous operation

### ISSUE THREAD

**Issue by Louies89** [mrphu3074/realm-query#6]
Hi, 
Is this library supports asynchronous Realm quaries?

**Comment by mrphu3074** [comment]
Basically, this lib only converts criteria object to criteria string (Realm query pattern).
But can you give an example of what you mean?

**Comment by Louies89** [comment]
@mrphu3074 
Please check my question [here](https://stackoverflow.com/questions/48756313/how-to-open-realmjavascript-object-asynchronously-and-use-it-with-services)
It has my example also.

As explained in realm [documentation ](https://realm.io/docs/javascript/latest/#synchronously-opening-realms)
the new Realm() is a synchronous call, which may block other quarries, but Realm.Open is asynchronous.

I am new to realm so not understanding the proper way to use it. Also there is no example for asynchronous use of realm.

**Comment by Louies89** [comment]
This issue can be closed.
